SET IDENTITY_INSERT [dbo].[MonAn] ON
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (1, N'Nem', N'Nem rán Việt Nam', CAST(50000.00 AS Decimal(10, 2)), 84)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (2, N'Gỏi cuốn', N'Gỏi cuốn tuoi ngon', CAST(40000.00 AS Decimal(10, 2)), 127)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (3, N'Phở', N'Phở bò truyền thống', CAST(60000.00 AS Decimal(10, 2)), 71)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (4, N'Bò Bún', N'Bò Bún thom ngon', CAST(70000.00 AS Decimal(10, 2)), 66)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (5, N'Mì xào', N'Mì xào h?i s?n', CAST(80000.00 AS Decimal(10, 2)), 60)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (6, N'Cơm gà', N'Cơm gà truyền thống', CAST(60000.50 AS Decimal(10, 2)), 120)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (7, N'Bánh xèo', N'Bánh xèo giòn rụm', CAST(50000.50 AS Decimal(10, 2)), 90)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (8, N'Lẩu thái', N'Lẩu thái chua cay', CAST(100000.00 AS Decimal(10, 2)), 50)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (9, N'Bún chả', N'Bún chả Hà Nội', CAST(70000.00 AS Decimal(10, 2)), 80)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (10, N'Chả cá', N'Chả cá Lã Vọng', CAST(80000.50 AS Decimal(10, 2)), 70)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (11, N'Bánh cuốn', N'Bánh cuốn nóng', CAST(40000.00 AS Decimal(10, 2)), 100)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (12, N'Gà nướng', N'Gà nướng muối ớt', CAST(90000.00 AS Decimal(10, 2)), 60)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (13, N'Cháo lòng', N'Cháo lòng thơm ngon', CAST(40000.50 AS Decimal(10, 2)), 90)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (14, N'Bò kho', N'Bò kho hương vị đậm đà', CAST(70000.50 AS Decimal(10, 2)), 70)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (15, N'Canh chua cá lóc', N'Canh chua đậm đà', CAST(60000.00 AS Decimal(10, 2)), 80)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (16, N'Bánh mì', N'Bánh mì thịt nguội', CAST(30000.00 AS Decimal(10, 2)), 200)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (17, N'Bánh canh', N'Bánh canh cua đậm đà', CAST(60000.50 AS Decimal(10, 2)), 80)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (18, N'Chả giò', N'Chả giò giòn tan', CAST(40000.50 AS Decimal(10, 2)), 90)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (19, N'Hủ tiếu', N'Hủ tiếu Nam Vang', CAST(70000.00 AS Decimal(10, 2)), 70)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (20, N'Lẩu gà', N'Lẩu gà lá giang', CAST(90000.00 AS Decimal(10, 2)), 60)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (21, N'Lẩu dê', N'Lẩu dê thảo mộc', CAST(120000.00 AS Decimal(10, 2)), 50)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (22, N'Mì Quảng', N'Mì Quảng đặc sản', CAST(70000.00 AS Decimal(10, 2)), 90)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (23, N'Cơm tấm', N'Cơm tấm sườn bì chả', CAST(60000.00 AS Decimal(10, 2)), 110)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (24, N'Gỏi gà', N'Gỏi gà hành tây', CAST(50000.00 AS Decimal(10, 2)), 90)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (25, N'Bánh hỏi', N'Bánh hỏi lòng heo', CAST(40000.00 AS Decimal(10, 2)), 100)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (26, N'Bún bò', N'Bún bò Huế cay nồng', CAST(70000.00 AS Decimal(10, 2)), 80)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (27, N'Bún riêu', N'Bún riêu cua đồng', CAST(60000.00 AS Decimal(10, 2)), 90)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (28, N'Bánh tét', N'Bánh tét lá chuối', CAST(30000.00 AS Decimal(10, 2)), 70)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (29, N'Xôi gà', N'Xôi gà xé thơm ngon', CAST(40000.00 AS Decimal(10, 2)), 120)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (30, N'Cháo gà', N'Cháo gà hành lá', CAST(50000.00 AS Decimal(10, 2)), 100)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (31, N'Trá đá', N'Trá đá mát lạnh', CAST(10000.00 AS Decimal(10, 2)), 500)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (32, N'Cafe sữa', N'Cafe sữa đá thơm ngon', CAST(20000.00 AS Decimal(10, 2)), 300)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (33, N'Nước cam', N'Nước cam nguyên chất', CAST(30000.00 AS Decimal(10, 2)), 200)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (34, N'Sinh tố bơ', N'Sinh tố bơ béo ngậy', CAST(30000.00 AS Decimal(10, 2)), 150)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (35, N'Nước dừa', N'Nước dừa tươi', CAST(30000.00 AS Decimal(10, 2)), 200)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (36, N'Sinh tố xoài', N'Sinh tố xoài ngọt mát', CAST(30000.00 AS Decimal(10, 2)), 100)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (37, N'Chanh dây', N'Nước chanh dây giải nhiệt', CAST(30000.00 AS Decimal(10, 2)), 150)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (38, N'Coca-cola', N'Nước ngọt Coca-cola', CAST(20000.50 AS Decimal(10, 2)), 400)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (39, N'Pepsi', N'Nước ngọt Pepsi', CAST(20000.00 AS Decimal(10, 2)), 350)
INSERT INTO [dbo].[MonAn] ([MaMonAn], [TenMonAn], [MoTa], [Gia], [SoLuong]) VALUES (40, N'Bia', N'Bia tươi', CAST(30000.50 AS Decimal(10, 2)), 200)
SET IDENTITY_INSERT [dbo].[MonAn] OFF
