INSERT INTO [dbo].[Ban] ([SoBan], [TrangThai]) VALUES (1, N'Đang phục vụ')
INSERT INTO [dbo].[Ban] ([SoBan], [TrangThai]) VALUES (2, N'Đang phục vụ')
INSERT INTO [dbo].[Ban] ([SoBan], [TrangThai]) VALUES (3, N'Đang phục vụ')
INSERT INTO [dbo].[Ban] ([SoBan], [TrangThai]) VALUES (4, N'Đang phục vụ')
INSERT INTO [dbo].[Ban] ([SoBan], [TrangThai]) VALUES (5, N'Đang phục vụ')
INSERT INTO [dbo].[Ban] ([SoBan], [TrangThai]) VALUES (6, N'Trống')
INSERT INTO [dbo].[Ban] ([SoBan], [TrangThai]) VALUES (7, N'Trống')
INSERT INTO [dbo].[Ban] ([SoBan], [TrangThai]) VALUES (8, N'Trống')
INSERT INTO [dbo].[Ban] ([SoBan], [TrangThai]) VALUES (9, N'Trống')
INSERT INTO [dbo].[Ban] ([SoBan], [TrangThai]) VALUES (10, N'Trống')
INSERT INTO [dbo].[Ban] ([SoBan], [TrangThai]) VALUES (11, N'Trống')
INSERT INTO [dbo].[Ban] ([SoBan], [TrangThai]) VALUES (12, N'Trống')
INSERT INTO [dbo].[Ban] ([SoBan], [TrangThai]) VALUES (13, N'Trống')
INSERT INTO [dbo].[Ban] ([SoBan], [TrangThai]) VALUES (14, N'Trống')
INSERT INTO [dbo].[Ban] ([SoBan], [TrangThai]) VALUES (15, N'Trống')
INSERT INTO [dbo].[Ban] ([SoBan], [TrangThai]) VALUES (16, N'Trống')
INSERT INTO [dbo].[Ban] ([SoBan], [TrangThai]) VALUES (17, N'Trống')
INSERT INTO [dbo].[Ban] ([SoBan], [TrangThai]) VALUES (18, N'Trống')
INSERT INTO [dbo].[Ban] ([SoBan], [TrangThai]) VALUES (19, N'Trống')
INSERT INTO [dbo].[Ban] ([SoBan], [TrangThai]) VALUES (20, N'Trống')
INSERT INTO [dbo].[Ban] ([SoBan], [TrangThai]) VALUES (21, N'Trống')
